permalink: /:year-:month-:day/:title/
title: ZerUniverse
email: zzy8200@gmail.com
description: On the way
url: https://gitblog.zzeyu.com

paginate: 5
paginate_path: "/page:num/"

navigation:
  - text: RSS
    url: https://gitblog.zzeyu.com/feed.xml
  - text: GitHub
    url: https://github.com/zeruniverse
  - text: Author
    url: https://zzeyu.com

# Build settings
markdown: kramdown
excerpt_separator: "<!--more-->"
highlighter: rouge

gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
